### ISSUE TITLE
some functions' API does not follow the style guide

### ISSUE THREAD

**Issue by berndbischl** [lbeggel/shapeletLib#1]
i can seen quite a few variables which contain upper cases

eg 
evaluateOofHinge = function(w, w0, lambda.W, Y, M) {

**Comment by berndbischl** [comment]
@lbeggel

**Comment by lbeggel** [comment]
i've updated the api. Next iteration needed @berndbischl

**Comment by berndbischl** [comment]
please browse through the function list yourself. I still see, after 30secs, many uppercase letters and underscores. 
also look at the body and interval vars. same thing.


lets get this sorted quickly pls
