### ISSUE TITLE
unify predict function

### ISSUE THREAD

**Issue by berndbischl** [lbeggel/shapeletLib#10]
there should only be one predict function and it should be an implementing method for the S3 generic predict of base R
DONE

you know from the model whether have binary or multiclass data, the user does not have to decide this and everything else can be handled through arguments
DONE

**Comment by berndbischl** [comment]
see #16

**Comment by lbeggel** [comment]
@berndbischl: is the implementing method for S3 correct ? (file: predict.R) 
If I do not specify the predict generic here, there is a warning.  However, it looks somehow strange to me.

**Comment by berndbischl** [comment]
1) you dont implement the generic "predict". that exists in base R. remove it.

2) shapeletModel is a class. So the first letter must be upper case. ShapeletModel.

3) 
```
  switch(classtype,
    Binary = {pred.class = predictClassBinary(model = object, data.test = newdata)},
    Multi = {pred.class = predictClassMulti(model = object, data.test = newdata)}
  )
```

dont do this. specialize the class in the return function. this is what s3 is good for. 
introduce ShapeletModelBinaryclass, ShapeletModelMulticlass, then use s3 dispatch instead of the swicth

**Comment by lbeggel** [comment]
I introduced the more specific classes ShapeletModelBinaryclass and ShapeletModelMulticlass (additional to ShapeletModel) and the makeClassification function for them to avoid the switch. Is this too much?

**Comment by berndbischl** [comment]
well :)

you want this

predict.ShapeletModelMulticlass
predict.ShapeletModelBinaryclass

get rid of 
predict.ShapeletModel
and makeClassification.*

i would suggest
