### ISSUE TITLE
learnShapelets API

### ISSUE THREAD

**Issue by berndbischl** [lbeggel/shapeletLib#11]
the labels should be a factor variable. 

you can also shorten the names, you dont need the ".train" in the names.

you also cannot refer to the docs of learnShapeLetsBinary as this is not exported

this seems to be a central function, you should at least provide one example with "@example"

**Comment by lbeggel** [comment]
should work now. is it ok that way?

**Comment by berndbischl** [comment]
- your docs still say label is "integer"

- and use "@example", not plural

- your returned list elements should also formally document the data type

**Comment by berndbischl** [comment]
and you are still referring to learnShapeLetsBinary?

**Comment by berndbischl** [comment]
you have to use \code{\link{foo}} to refer to such stuff, then the user can click an such links (if they would link to existing stuff...), or " R CMD check" will report an error here, because there is no doc page for that name, as in your case

**Comment by lbeggel** [comment]
Please check if it is ok now.

**Comment by berndbischl** [comment]
can you really please answer my individual points indiviudally, a simple "DONE" below each one is enough. Because then you will see yourself that at least one is missing....

**Comment by lbeggel** [comment]
I looked it up in "R packages" why using only @example causes errors: there it says that @example needs a path to a separate example-file.
