### ISSUE TITLE
dontrun in examples

### ISSUE THREAD

**Issue by berndbischl** [lbeggel/shapeletLib#13]
why are you using that?

**Comment by lbeggel** [comment]
Mainly to speed things up. Is it better style  to run it?

**Comment by berndbischl** [comment]
i would advise to keep the examples so small / fast that you can safely remove the "dontrun"

you want them be automatically checked whether they contain errors

you can run the "dontrun" stuff with R CMD check, but you need to pass a specific argument for this and not forget this: in short: lets try to keep this simple and do what i wrote above :)

**Comment by berndbischl** [comment]
and i just now copied your example code from learnShapelets to an extra file, without modifications.
and guess what: it does not run....

```
Loading shapeletLib
Error in source("test.R") : 
  Assertion on 'step' failed: Must be element of set {'pegasos','sqrt','user'}.
```

**Comment by berndbischl** [comment]
and really enable travis first, see #4
