### ISSUE TITLE
set.seed called internally!

### ISSUE THREAD

**Issue by berndbischl** [lbeggel/shapeletLib#15]
never ever do that. 

learnShapeletsMulti <- function(method, k, l, lambda, c.reg, data, label, step, 

line 58: set.seed(1)

**Comment by lbeggel** [comment]
ups. removed.

**Comment by berndbischl** [comment]
i can still see this commented out in 

```
R/learnShapelets.R
60:#'  set.seed(100)
```

more important:

```
tests/testthat/test_initializeShapelets.R
8:  set.seed(100)
tests/testthat/test_learnShapelets.R
5:  set.seed(100)
tests/testthat/test_makeShapeletTrafo.R
5:  set.seed(10)
tests/testthat/test_sigmoid.R
7:  set.seed(10)
tests/testthat/test_predictDataClass.R
5:  set.seed(100)
```

also dont do this in the tests. you can set a global seed in a file called helper_zzz.R in the tests/testhat subdir. do you want to do that?

**Comment by lbeggel** [comment]
Removed the seeding in the files i had forgotten in the first iteration. 
I think the seeding will not be necessary in an additional helper file.

**Comment by berndbischl** [comment]
Seeding the tests in helper_zzz is actually a good idea. Just do this.

**Comment by lbeggel** [comment]
Added the helper_zzz.R file
