### ISSUE TITLE
use checkmate to ensure all input args are of the expected class.

### ISSUE THREAD

**Issue by giuseppec** [lbeggel/shapeletLib#17]

**Comment by lbeggel** [comment]
Bernd's advice was to only check in the exported functions (first). In the other functions also necessary?

**Comment by berndbischl** [comment]
> Bernd's advice was to only check in the exported functions (first). In the other functions also necessary?

exported is most important now. you can add more checks if you run into problems (because they are missing)

so if you have checks in all exported stuff, close here
