### ISSUE TITLE
export only minimal API

### ISSUE THREAD

**Issue by berndbischl** [lbeggel/shapeletLib#5]
think about what you want to export, post the list here, and remove the export tags

**Comment by lbeggel** [comment]
initializeShapelets:  K initial shapelets from the given TS set
learnShapelets: learns the optimal shapelets
makeShapeletTrafo:  shapelet-based transformation given set of shapelets and raw TS
measureAcc: accuracy 
measureMcr: missclassification rate
plotOof: plot the learning function over the learning iterations
plotShapelets: plot a given set of shapelets
predictDataClass: predicts the class of a given set of TS under the learned shapelet model
predLinearModelY: predicts the linear model under a learned shapelet model (binary)
predLinearModelMulti: predicts the linear model under a learned shapelet model (multiclass)
segmentingCpp: extracts all potential shapelets of length L of a given set of TS

**Comment by berndbischl** [comment]
> initializeShapelets: K initial shapelets from the given TS set

> learnShapelets: learns the optimal shapelets
> makeShapeletTrafo: shapelet-based transformation given set of shapelets and raw TS
> measureAcc: accuracy
> measureMcr: missclassification rate
> plotOof: plot the learning function over the learning iterations
> plotShapelets: plot a given set of shapelets
> predictDataClass: predicts the class of a given set of TS under the learned shapelet model
> predLinearModelY: predicts the linear model under a learned shapelet model (binary)
> predLinearModelMulti: predicts the linear model under a learned shapelet model (multiclass)
> segmentingCpp: extracts all potential shapelets of length L of a given set of TS



> measureAcc: accuracy
> measureMcr: missclassification rate

remove those, at least unexport them, there are other packages like mlr for evaluation like this, stop at having a clean train and predict function

**Comment by berndbischl** [comment]
> predLinearModelY: predicts the linear model under a learned shapelet model (binary)
> predLinearModelMulti: predicts the linear model under a learned shapelet model (multiclass)

i have no idea what this does and whether one would need this
