### ISSUE TITLE
use checkmate to validate user input

### ISSUE THREAD

**Issue by berndbischl** [lbeggel/shapeletLib#7]
see here 
https://github.com/mllg/checkmate

for examples look into the source of any of my packages

**Comment by berndbischl** [comment]
at least do this for (reasonably) exported function, see #5

**Comment by lbeggel** [comment]
Added.

**Comment by berndbischl** [comment]
thx. a few comments

1) 
```
  if (!is.null(lambda)) {
    assertNumber(lambda)
  }
```
you dont need this "ifs", use "null.ok = TRUE"

2) 
  assertIntegerish(max.iter)
-->
max.iter = asCount(max.initer)

the "as" function does the arg check, but also converts to a clean int. "Count" means it is a pos int (what you forgot to check anyway...)

3) in the places you use assertMatrix, you very likely want to check more. like the mode = "numeric".
min rows and min cols.
